In [ ]:
import numpy as np

#Input matrix
X = np.array([[7, 5, 0, 0, 3, 2],
             [6, 4, 5, 1, 4, 8],
             [9, 0, 2, 2, 5, 4],
             [6, 3, 4, 7, 9, 8],
             [5, 7, 5, 6, 9, 0],
             [7, 9, 0, 8, 2, 3]])

#Filter matrix
f = np.array([[1, 0, -1],
             [2, 0, -2],
             [1, 0, -1]])

W1 = X.shape[0]  #width f input
H1 = X.shape[1]  #height of input
C = 1            #depth of input
P = 0            #padding size
F = f.shape[0]   #Filter size (for square filter)
S = 1            #stride
K = 1            #number of filters (also the depth of output activation map)

print("Size of the input: ",X.shape)
print("Size of the kernel: ",f.shape)
print("Number of parameters (considering the bias): ",F**2*C + 1)

#Output dimension calculation
W2 = (W1-F+2*P)/S + 1   #width of the output activation map
H2 = (H1-F+2*P)/S + 1   #height of the output activation map
#depth of output activation map will be K = 1

print("\nWidth of the output activation map: ",W2)
print("Height of the output activation map: ",H2)

Size of the input:  (6, 6)
Size of the kernel:  (3, 3)
Number of parameters (considering the bias):  10

Width of the output activation map:  4.0
Height of the output activation map:  4.0


In [ ]:
#Create the output activation map
W2 = int(W2)
H2 = int(H2)
A = np.zeros([H2,W2])
for r in range(H2):
  for c in range(W2):
    A[r,c] = np.sum(f*X[r:r+F,c:c+F])
print("\nOutput activation map:\n",A)


Output activation map:
 [[ 16.   9.  -4. -18.]
 [ 17.  -5. -10. -12.]
 [ 11.  -9. -17.   2.]
 [  9.  -1. -15.  16.]]


In [ ]:
#Apply maxpooling
m = 2 #2 by 2 maxpooling
H3 = int(H2/m)
W3 = int(W2/m)
M = np.zeros([H3,W3])
for r in range(H3):
  for c in range(W3):
    M[r,c] = np.max(A[m*r:2*r+m,m*c:m*c+m])
print("\nOutput after maxpooling:\n",M)


Output after maxpooling:
 [[17. -4.]
 [11. 16.]]
